### ISSUE TITLE
Electron chrome driver error for Mac m3 pro sonoma 14.5

### ISSUE THREAD

**Issue by seshu2020** [electron/chromedriver#148]
<img width="293" height="300" alt="Screenshot 2024-07-16 at 10 43 39 PM" src="https://github.com/user-attachments/assets/f659fc87-c380-4abc-81de-0801fd2992cc">

while doing npm install --save-dev electron getting below error 

npm WARN deprecated electron-download@4.1.1: Please use @electron/get moving forward.
npm ERR! code 1
npm ERR! path /Users/2229275/caseys_fe/commerce-oms/node_modules/spectron/node_modules/electron-chromedriver
npm ERR! command failed
npm ERR! command sh -c node ./download-chromedriver.js
npm ERR! /Users/2229275/caseys_fe/commerce-oms/node_modules/spectron/node_modules/electron-chromedriver/download-chromedriver.js:30
npm ERR!   if (err != null) throw err
npm ERR!                    ^
npm ERR! 
npm ERR! Error: Failed to find Electron v1.8.0 for darwin-arm64 at https://github.com/electron/electron/releases/download/v1.8.0/chromedriver-v1.8.0-darwin-arm64.zip
npm ERR!     at Request.<anonymous> (/Users/2229275/caseys_fe/commerce-oms/node_modules/nugget/index.js:197:61)
npm ERR!     at Request.emit (node:events:513:28)
npm ERR!     at Request.onRequestResponse (/Users/2229275/caseys_fe/commerce-oms/node_modules/request/request.js:1059:10)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:542:22)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at addChunk (node:internal/streams/readable:324:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:297:9)
npm ERR! 
npm ERR! Node.js v18.16.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/2229275/.npm/_logs/2024-07-17T04_21_09_136Z-debug-0.log

same issue getting when i switched to rosetta 2 from terminal

**Comment by MarshallOfSound** [comment]
Thanks for the report. This comes from Spectron pinning an old bundled chromedriver; the current repo uses @electron/get with a semver fallback, and there was no response since filing, so we are closing it. Please open a fresh issue if you reproduce it with current electron-chromedriver.
