### ISSUE TITLE
Can't install on ubuntu

### ISSUE THREAD

**Issue by evertonfraga** [electron/chromedriver#4]
Maybe because the node package on ubuntu is `nodejs` instead of only `node`.

Any help?

Log:
```
$ npm install electron-chromedriver 
npm WARN package.json esprima@2.5.0 scripts['tests'] should probably be scripts['test'].
npm WARN package.json get-package-info@0.0.2 No repository field.
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
|
> electron-chromedriver@1.2.0 install /home/ubuntu/Projects/myproject/node_modules/electron-chromedriver
> node ./download-chromedriver.js


/home/ubuntu/Projects/myproject/node_modules/readable-stream/lib/_stream_transform.js:159
  throw new Error('not implemented');
        ^
Error: not implemented
    at Transform._transform (/home/ubuntu/Projects/myproject/node_modules/readable-stream/lib/_stream_transform.js:159:9)
    at Transform._read (/home/ubuntu/Projects/myproject/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/ubuntu/Projects/myproject/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/ubuntu/Projects/myproject/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/ubuntu/Projects/myproject/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/home/ubuntu/Projects/myproject/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/home/ubuntu/Projects/myproject/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/ubuntu/Projects/myproject/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at /home/ubuntu/Projects/myproject/node_modules/readable-stream/lib/_stream_readable.js:600:7
    at process._tickCallback (node.js:415:13)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! electron-chromedriver@1.2.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.2.0 install script.
npm ERR! This is most likely a problem with the electron-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./download-chromedriver.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.19.0-15-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron-chromedriver"
npm ERR! cwd /home/ubuntu/Projects/myproject
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/Projects/myproject/npm-debug.log
npm ERR! not ok code 0
```

**Comment by kevinsawicki** [comment]
> npm ERR! node -v v0.10.25
> npm ERR! npm -v 1.4.21

It looks like you are using a very old version of node and npm, could you try upgrading to the latest LTS release, 4.5.0, and see if this issue persists?

**Comment by evertonfraga** [comment]
you were right. this was a rather old VM setup. It's all working now, thank you.
