### ISSUE TITLE
Chromedriver exited with error code: null error (MacOS)

### ISSUE THREAD

**Issue by cenkingunlugu** [electron/chromedriver#41]
For a project, I am trying to run electron-chromedriver but I am getting these errors:

```
./node_modules/.bin/chromedriver -h                   

dyld: Library not loaded: @rpath/libffmpeg.dylib
  Referenced from: /Users/cxe10/workspace/FluxToolUiTests/node_modules/electron-chromedriver/bin/chromedriver
  Reason: image not found
/Users/cxe10/workspace/FluxToolUiTests/node_modules/electron-chromedriver/chromedriver.js:18
    throw new Error(`Chromedriver exited with error code: ${code}`)
    ^

Error: Chromedriver exited with error code: null
    at ChildProcess.chromeDriverProcess.on.code (/Users/cxe10/workspace/FluxToolUiTests/node_modules/electron-chromedriver/chromedriver.js:18:11)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

MacOSX Version: 10.14.4 (18E226)
Node Version: v10.15.3
Npm Version: 6.4.1
electron-chromedriver version: ^5.0.0-beta.1

**Comment by PedroPauloML** [comment]
Same error

**Comment by mandaarp** [comment]
For me as well.

**Comment by evertonlperes** [comment]
Got the same error in CI, running on macOS BigSur:

```bash
── electron@12.1.0
└─┬ spectron@14.0.0
  └─┬ @electron/remote@1.2.1
    └── electron@12.1.0 deduped

└─┬ spectron@14.0.0
  └── electron-chromedriver@12.0.0
```
Have you guys found a solution?

Thanks!

**Comment by SNDST00M** [comment]
I personally found that most if not all driver related errors I ever had were handled by using `selenium-webdriver`.

**Comment by MarshallOfSound** [comment]
Thanks for the report. This is a packaging/extraction problem in a very old release with only me-too comments and no actionable repro, abandoned since 2021, so we are closing it as stale. Please open a fresh issue if it still occurs on a current version.
