### ISSUE TITLE
Download script fails when behind proxy

### ISSUE THREAD

**Issue by dtel** [electron/chromedriver#42]
The download script fails behind a corporate proxy despite setting npm proxy & https-proxy variables. Npm works okay for downloading other required packages.

> electron-chromedriver@3.0.0 install C:\electron-api-demos\node_modules\electron-chromedriver
> node ./download-chromedriver.js

C:\electron-api-demos\node_modules\electron-chromedriver\download-chromedriver.js:19
  if (err != null) throw err
                   ^

Error: tunneling socket could not be established, statusCode=407
    at ClientRequest.onConnect (C:\electron-api-demos\node_modules\tunnel-agent\index.js:166:19)
    at ClientRequest.g (events.js:291:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:395:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by Trebolman** [comment]
Could you fix it?

**Comment by nicoalee** [comment]
Also facing this issue. Was there any resolution?

**Comment by robertpatrick** [comment]
Have you looked at the @electron/get project instructions?  Assuming you are using a modern version of Electron, I would expect setting the following environment variables to allow this to work:

```
export ELECTRON_GET_USE_PROXY=true
export HTTPS_PROXY=<your proxy server url>
export NO_PROXY=<your no proxy list>
```

**Comment by MarshallOfSound** [comment]
Thanks for the report! The old download-chromedriver.js this refers to has been replaced, downloads now go through @electron/get, which supports proxies via ELECTRON_GET_USE_PROXY plus HTTPS_PROXY/NO_PROXY. The original code path is gone, so closing as resolved.
