### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by chxry** [electron/chromedriver#66]
When running npm install the following error occurs:

 node ./download-chromedriver.js

internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (G:\code\js\angular-electron\node_modules\electron-chromedriver\node_modules\extract-zip\index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\code\js\angular-electron\node_modules\electron-chromedriver\download-chromedriver.js:4:20)

**Comment by chxry** [comment]
fixed by reinstalling node.js
