### ISSUE TITLE
line 6 in chromedriver.js

### ISSUE THREAD

**Issue by jk-64** [electron/chromedriver#75]
Hi,

I'm trying to launch Spectron.
app is lauched but webContents and others commands are undefined.

If I understand, chromedriver does the link between electron and spectron.

I remarked that line in the file chromedriver.js: const command = **path.join(__dirname, 'bin', 'chromedriver')**
The path is then : '/path/to/application/**node_modules/electron-chromedriver/bin/chromedriver**"

On my system, there is only one file in the bin directory: LICENSES.chromium.html

I was wondering if there isn't a connection with those undefined commands.
Thanks

**Comment by jk-64** [comment]
I add:  
$ chromedriver -h
 
/path/to/application/node_modules/electron-chromedriver/chromedriver.js:22
chromeDriverProcess.on('error', error => { throw new Error(error) })
                                           ^

Error: Error: spawn /path/to/application/node_modules/electron-chromedriver/bin/chromedriver ENOENT
    at ChildProcess.<anonymous> (/path/to/application/node_modules/electron-chromedriver/chromedriver.js:22:50)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
